### ISSUE TITLE
Question about mvsec data processing

### ISSUE THREAD

**Issue by fairy003** [tudelft/idnet#4]
I wanted to train MVSEC data with dt =1 but failed to load dataset.
  In the else branch of loader_mvsec.py, specifically designed for dt=1 or dt=4, the script attempts to access crucial data from {seq_name}.h5. But I found that I didn't have the "seq_name}.h5" file 
```
else:
            assert self.dt == 1 or self.dt == 4
            self.h5 = h5py.File(os.path.join(seq_path, f"{seq_name}.h5"), "r")
            self.event = self.h5['events']
            self.timestamps = self.h5['flow']['dt={}'.format(self.dt)]['timestamps'][:, 0]
            self.gt_flow = list(self.h5['flow']['dt={}'.format(self.dt)].keys())
            self.gt_flow.remove('timestamps')
            assert sorted(self.gt_flow) == self.gt_flow
          
"
```
I want to know what is the (seq_name).h5 file. Is it the extra data processing file？Can you provide me the file?THANKS A LOT

**Comment by yilun-wu** [comment]
Apologies for my negligence over this issue...

Indeed, this is a custom file we created ourselves. The generating script is under https://github.com/tudelft/idnet/blob/master/idn/scripts/format_mvsec/format_mvsec.py
