### ISSUE TITLE
DSEC checkpoints

### ISSUE THREAD

**Issue by AiladReb** [tudelft/idnet#5]
Hello,  Thank you very much for your work.

Would you mind sharing the checkpoints for DSEC dataset, please?

**Comment by yilun-wu** [comment]
The checkpoints are under https://github.com/tudelft/idnet/tree/master/idn/checkpoint
Note these .pt files are managed by git-lfs, so you'd need to install it on your system in order to pull the weights. Or you could manually download them from the github webpage.
