### ISSUE TITLE
For the training of ID

### ISSUE THREAD

**Issue by ZPJ-LEFT** [tudelft/idnet#6]
Hello, I am confused that the performance of ID in the paper is inconsistent.

In Table I, the metrics of EPE for ID (4 iters, 1/4 resolution) and ID (4 iters, 1/8 resolution) are 0.72 and 0.77. Based on the checkpoints you have released, these results are correct indeed.

![image](https://github.com/user-attachments/assets/6b259b11-a42d-4d3f-8543-1e7feab6e38b)

However, in the ablation experiments, the results changed. 
In Table IV, the metric of EPE for ID (4 iters) is only 0.88.
![image](https://github.com/user-attachments/assets/34ad5414-bb52-482e-ba38-0e2b48e84c4b)
And in Table VI, the metric of EPE for ID (1/8 resolution) is only 0.79.
![image](https://github.com/user-attachments/assets/eae11312-c353-4f15-a691-ee9b76f48a4b)

I would like to ask why the performance of the model in Table I is significantly higher than that in Table IV and Table VI. Compared to the training configuration described in Section IV A, are there any changes？

**Comment by yilun-wu** [comment]
This is because, as we mentioned in the title of Table IV, we used a smaller model (with less feature channels for the encoder and convgru) to do the ablation studies.

**Comment by ZPJ-LEFT** [comment]
Sorry, I didn't notice it before. Thank you for your help.
